Document: ninjam-client
Title: Debian ninjam-client Manual
Author: <insert document author here>
Abstract: This manual describes what ninjam-client is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ninjam-client/ninjam-client.sgml.gz

Format: postscript
Files: /usr/share/doc/ninjam-client/ninjam-client.ps.gz

Format: text
Files: /usr/share/doc/ninjam-client/ninjam-client.text.gz

Format: HTML
Index: /usr/share/doc/ninjam-client/html/index.html
Files: /usr/share/doc/ninjam-client/html/*.html

  
